create extension if not exists pgcrypto;

create type public.user_role as enum ('user', 'manager', 'admin');
create type public.check_status as enum (
  'new',
  'pending',
  'reviewed',
  'discussion_required',
  'completed',
  'overdue'
);
create type public.action_taken as enum (
  'removed',
  'left_on_shelf',
  'discounted',
  'returned',
  'checked_ok',
  'not_found',
  'other'
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  store_code text not null,
  store_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint uq_stores_store_code unique (store_code)
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users (id) on delete set null,
  store_id bigint not null references public.stores (id) on update cascade on delete restrict,
  name text not null,
  surname text not null,
  user_chat_id bigint not null,
  role public.user_role not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint uq_users_user_chat_id unique (user_chat_id)
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  article text not null,
  barcode text not null,
  product_name text not null,
  units_of_measurement text not null,
  category text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint uq_products_barcode unique (barcode)
);

create table if not exists public.product_batches (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on update cascade on delete restrict,
  store_id bigint not null references public.stores (id) on update cascade on delete restrict,
  quantity integer not null check (quantity >= 0),
  expiry_date date not null,
  delivery_date date,
  notified boolean not null default false,
  notified_at timestamptz,
  notified_days integer not null default 7 check (notified_days >= 0),
  check_status public.check_status not null default 'new',
  checked_by_user_id bigint references public.users (id) on update cascade on delete set null,
  checked_at timestamptz,
  action_taken public.action_taken,
  action_note text,
  discussion_required boolean not null default false,
  discussion_note text,
  discussion_requested_by_user_id bigint references public.users (id) on update cascade on delete set null,
  discussion_requested_at timestamptz,
  admin_decision text,
  admin_decision_note text,
  admin_decision_by_user_id bigint references public.users (id) on update cascade on delete set null,
  admin_decision_at timestamptz,
  created_by_user_id bigint references public.users (id) on update cascade on delete set null,
  updated_by_user_id bigint references public.users (id) on update cascade on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint uq_product_batches_operational unique (product_id, store_id, expiry_date),
  constraint chk_product_batches_other_action_note
    check (action_taken is distinct from 'other'::public.action_taken or nullif(btrim(action_note), '') is not null),
  constraint chk_product_batches_discussion_note
    check (discussion_required = false or nullif(btrim(discussion_note), '') is not null)
);

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on update cascade on delete restrict,
  action_type text not null,
  batch_id bigint references public.product_batches (id) on update cascade on delete set null,
  product_id bigint references public.products (id) on update cascade on delete set null,
  store_id bigint references public.stores (id) on update cascade on delete set null,
  old_quantity integer,
  new_quantity integer,
  old_expiry_date date,
  new_expiry_date date,
  comment text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.notification_log (
  id bigint generated by default as identity primary key,
  batch_id bigint references public.product_batches (id) on update cascade on delete set null,
  product_id bigint references public.products (id) on update cascade on delete set null,
  store_id bigint references public.stores (id) on update cascade on delete set null,
  user_id bigint references public.users (id) on update cascade on delete set null,
  notification_type text not null,
  message_text text not null,
  sent_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on update cascade on delete cascade,
  session_key text not null,
  session_state jsonb not null default '{}'::jsonb,
  expires_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint uq_user_sessions_user_key unique (user_id, session_key)
);

create index if not exists idx_users_store_id on public.users (store_id);
create index if not exists idx_users_auth_user_id on public.users (auth_user_id);
create index if not exists idx_products_article on public.products (article);
create index if not exists idx_products_category on public.products (category);
create index if not exists idx_product_batches_store_status on public.product_batches (store_id, check_status);
create index if not exists idx_product_batches_expiry_date on public.product_batches (expiry_date);
create index if not exists idx_product_batches_notified on public.product_batches (notified, notified_days);
create index if not exists idx_activity_log_user_id on public.activity_log (user_id);
create index if not exists idx_activity_log_batch_id on public.activity_log (batch_id);
create index if not exists idx_activity_log_product_id on public.activity_log (product_id);
create index if not exists idx_activity_log_store_id on public.activity_log (store_id);
create index if not exists idx_notification_log_batch_id on public.notification_log (batch_id);
create index if not exists idx_notification_log_product_id on public.notification_log (product_id);
create index if not exists idx_notification_log_store_id on public.notification_log (store_id);
create index if not exists idx_notification_log_user_id on public.notification_log (user_id);
create index if not exists idx_user_sessions_expires_at on public.user_sessions (expires_at);

drop trigger if exists trg_stores_set_updated_at on public.stores;
create trigger trg_stores_set_updated_at
before update on public.stores
for each row execute function public.set_updated_at();

drop trigger if exists trg_users_set_updated_at on public.users;
create trigger trg_users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists trg_products_set_updated_at on public.products;
create trigger trg_products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists trg_product_batches_set_updated_at on public.product_batches;
create trigger trg_product_batches_set_updated_at
before update on public.product_batches
for each row execute function public.set_updated_at();

drop trigger if exists trg_user_sessions_set_updated_at on public.user_sessions;
create trigger trg_user_sessions_set_updated_at
before update on public.user_sessions
for each row execute function public.set_updated_at();
