alter table public.product_batches
add column if not exists intake_note text;

create table if not exists public.notification_settings (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.stores (id) on update cascade on delete cascade,
  enabled boolean not null default false,
  chat_id text not null default '',
  send_time time not null default '08:00',
  days_before integer not null default 7 check (days_before >= 1 and days_before <= 30),
  last_sent_date date,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint uq_notification_settings_store_id unique (store_id)
);

create table if not exists public.telegram_bot_state (
  bot_key text primary key,
  last_update_id bigint,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_notification_settings_store_id on public.notification_settings (store_id);

drop trigger if exists trg_notification_settings_set_updated_at on public.notification_settings;
create trigger trg_notification_settings_set_updated_at
before update on public.notification_settings
for each row execute function public.set_updated_at();

drop trigger if exists trg_telegram_bot_state_set_updated_at on public.telegram_bot_state;
create trigger trg_telegram_bot_state_set_updated_at
before update on public.telegram_bot_state
for each row execute function public.set_updated_at();

insert into public.telegram_bot_state (bot_key, last_update_id)
values ('default', null)
on conflict (bot_key) do nothing;

create or replace view public.api_stores_v as
select
  s.id,
  s.store_code as code,
  coalesce(s.store_name, s.store_code) as name,
  s.is_active
from public.stores s;

create or replace function public.api_employee_activity_log(p_user_id bigint, p_limit integer default 10)
returns jsonb
language sql
stable
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'at', to_char(src.created_at at time zone 'utc', 'YYYY-MM-DD HH24:MI'),
        'action', coalesce(nullif(btrim(src.comment), ''), src.action_type)
      )
      order by src.created_at desc
    ),
    '[]'::jsonb
  )
  from (
    select al.created_at, al.action_type, al.comment
    from public.activity_log al
    where al.user_id = p_user_id
    order by al.created_at desc
    limit greatest(coalesce(p_limit, 10), 1)
  ) as src;
$$;

create or replace view public.api_employees_v as
select
  u.id,
  u.name,
  u.surname,
  concat_ws(' ', u.name, u.surname) as full_name,
  u.role::text as role,
  s.id as store_id,
  coalesce(s.store_name, s.store_code) as store_name,
  u.user_chat_id::text as telegram_client_id,
  case
    when u.is_active then 'на зміні'
    else 'відсутній'
  end as status,
  coalesce(to_char(last_log.created_at at time zone 'utc', 'YYYY-MM-DD HH24:MI'), to_char(u.updated_at at time zone 'utc', 'YYYY-MM-DD HH24:MI')) as last_activity_at,
  coalesce(nullif(btrim(last_log.comment), ''), last_log.action_type, 'Ще немає дій') as last_action,
  public.api_employee_activity_log(u.id, 10) as activity_log
from public.users u
join public.stores s on s.id = u.store_id
left join lateral (
  select al.created_at, al.action_type, al.comment
  from public.activity_log al
  where al.user_id = u.id
  order by al.created_at desc
  limit 1
) as last_log on true;

create or replace view public.api_products_v as
select
  pb.id,
  p.product_name as name,
  p.category,
  p.barcode,
  null::text as image_url,
  coalesce(to_char(pb.delivery_date, 'YYYY-MM-DD'), to_char(pb.expiry_date, 'YYYY-MM-DD')) as batch,
  pb.store_id,
  pb.quantity,
  coalesce(to_char(pb.delivery_date, 'YYYY-MM-DD'), '') as received_at,
  to_char(pb.expiry_date, 'YYYY-MM-DD') as expires_at,
  pb.check_status::text as status,
  coalesce(pb.intake_note, '') as notes,
  coalesce(pb.checked_by_user_id, pb.created_by_user_id, pb.updated_by_user_id) as received_by_user_id,
  p.id as product_id
from public.product_batches pb
join public.products p on p.id = pb.product_id;

create or replace function public.api_employee_by_chat_id(p_user_chat_id bigint)
returns setof public.api_employees_v
language sql
stable
as $$
  select *
  from public.api_employees_v
  where telegram_client_id = p_user_chat_id::text
  limit 1;
$$;

create or replace function public.api_get_notification_settings(p_store_id bigint default public.current_store_id())
returns table (
  enabled boolean,
  chat_id text,
  send_time text,
  days_before integer,
  last_sent_date text
)
language sql
stable
as $$
  select
    ns.enabled,
    ns.chat_id,
    to_char(ns.send_time, 'HH24:MI') as send_time,
    ns.days_before,
    case
      when ns.last_sent_date is null then null
      else to_char(ns.last_sent_date, 'YYYY-MM-DD')
    end as last_sent_date
  from public.notification_settings ns
  where ns.store_id = p_store_id
  limit 1;
$$;

create or replace function public.api_upsert_notification_settings(
  p_store_id bigint,
  p_enabled boolean,
  p_chat_id text,
  p_send_time text,
  p_days_before integer,
  p_last_sent_date date default null
)
returns public.notification_settings
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.notification_settings;
begin
  insert into public.notification_settings (
    store_id,
    enabled,
    chat_id,
    send_time,
    days_before,
    last_sent_date
  )
  values (
    p_store_id,
    coalesce(p_enabled, false),
    coalesce(p_chat_id, ''),
    coalesce(p_send_time, '08:00')::time,
    greatest(coalesce(p_days_before, 7), 1),
    p_last_sent_date
  )
  on conflict (store_id) do update
  set
    enabled = excluded.enabled,
    chat_id = excluded.chat_id,
    send_time = excluded.send_time,
    days_before = excluded.days_before,
    last_sent_date = coalesce(excluded.last_sent_date, public.notification_settings.last_sent_date)
  returning * into v_row;

  return v_row;
end;
$$;

create or replace function public.api_update_telegram_state(p_last_update_id bigint)
returns public.telegram_bot_state
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.telegram_bot_state;
begin
  insert into public.telegram_bot_state (bot_key, last_update_id)
  values ('default', p_last_update_id)
  on conflict (bot_key) do update
  set last_update_id = excluded.last_update_id
  returning * into v_row;

  return v_row;
end;
$$;

create or replace function public.api_get_telegram_state()
returns public.telegram_bot_state
language sql
stable
security definer
set search_path = public
as $$
  select *
  from public.telegram_bot_state
  where bot_key = 'default'
  limit 1;
$$;

create or replace function public.api_upsert_product_and_batch(
  p_article text,
  p_barcode text,
  p_product_name text,
  p_units_of_measurement text,
  p_category text,
  p_store_id bigint,
  p_quantity integer,
  p_received_at date,
  p_expiry_date date,
  p_intake_note text,
  p_actor_user_id bigint
)
returns setof public.api_products_v
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product_id bigint;
  v_batch_id bigint;
begin
  insert into public.products (
    article,
    barcode,
    product_name,
    units_of_measurement,
    category
  )
  values (
    coalesce(nullif(btrim(p_article), ''), p_barcode),
    btrim(p_barcode),
    btrim(p_product_name),
    coalesce(nullif(btrim(p_units_of_measurement), ''), 'pcs'),
    coalesce(nullif(btrim(p_category), ''), 'Без категорії')
  )
  on conflict (barcode) do update
  set
    article = excluded.article,
    product_name = excluded.product_name,
    units_of_measurement = excluded.units_of_measurement,
    category = excluded.category
  returning id into v_product_id;

  insert into public.product_batches (
    product_id,
    store_id,
    quantity,
    expiry_date,
    delivery_date,
    intake_note,
    created_by_user_id,
    updated_by_user_id
  )
  values (
    v_product_id,
    p_store_id,
    greatest(coalesce(p_quantity, 0), 0),
    p_expiry_date,
    p_received_at,
    p_intake_note,
    p_actor_user_id,
    p_actor_user_id
  )
  on conflict (product_id, store_id, expiry_date) do update
  set
    quantity = excluded.quantity,
    delivery_date = excluded.delivery_date,
    intake_note = excluded.intake_note,
    updated_by_user_id = excluded.updated_by_user_id
  returning id into v_batch_id;

  return query
  select *
  from public.api_products_v
  where id = v_batch_id;
end;
$$;

create or replace function public.api_update_product_batch_status(
  p_batch_id bigint,
  p_check_status public.check_status,
  p_actor_user_id bigint,
  p_action_taken public.action_taken default null,
  p_action_note text default null
)
returns setof public.api_products_v
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.product_batches
  set
    check_status = p_check_status,
    checked_by_user_id = p_actor_user_id,
    checked_at = timezone('utc', now()),
    action_taken = p_action_taken,
    action_note = p_action_note,
    updated_by_user_id = p_actor_user_id
  where id = p_batch_id;

  return query
  select *
  from public.api_products_v
  where id = p_batch_id;
end;
$$;

alter table public.notification_settings enable row level security;
alter table public.telegram_bot_state enable row level security;

grant select, insert, update on public.notification_settings to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists notification_settings_select_same_store on public.notification_settings;
create policy notification_settings_select_same_store
on public.notification_settings
for select
to authenticated
using (store_id = public.current_store_id());

drop policy if exists notification_settings_upsert_same_store on public.notification_settings;
create policy notification_settings_upsert_same_store
on public.notification_settings
for insert
to authenticated
with check (store_id = public.current_store_id());

drop policy if exists notification_settings_update_same_store on public.notification_settings;
create policy notification_settings_update_same_store
on public.notification_settings
for update
to authenticated
using (store_id = public.current_store_id())
with check (store_id = public.current_store_id());
